/*
 * File: app/store/SessionStore.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CareMe.store.SessionStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.LocalStorage',
        'CareMe.model.Session'
    ],

    config: {
        clearOnPageLoad: false,
        data: {
            session: '7d952d4b-efd6-44ab-b09c-c4f4a1b5f1bd',
            email: 'kokboon@gmail.com'
        },
        model: 'CareMe.model.Session',
        storeId: 'SessionStore',
        proxy: {
            type: 'localstorage',
            id: 'careme-session'
        }
    }
});