/*
 * File: app/view/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CareMe.view.LoginPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginpanel',

    config: {
        title: '',
        html: '',
        margin: '',
        ui: '',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'image',
                centered: false,
                docked: 'top',
                height: '100px',
                left: '',
                margin: '30px 25%',
                padding: '80px',
                style: 'background-repeat: no-repeat;background-size: auto 100%;background-position:center',
                ui: 'light',
                width: '100px',
                src: 'image/login-logo.jpg'
            },
            {
                xtype: 'fieldset',
                docked: 'top',
                margin: '20px',
                title: '',
                items: [
                    {
                        xtype: 'textfield',
                        title: '',
                        itemId: 'userNameTextField',
                        label: '',
                        name: 'userNameTextField',
                        required: true,
                        placeHolder: 'Username'
                    },
                    {
                        xtype: 'passwordfield',
                        itemId: 'passwordTextField',
                        label: '',
                        name: 'passwordTextField',
                        required: true,
                        placeHolder: 'Password'
                    },
                    {
                        xtype: 'button',
                        docked: 'bottom',
                        id: '',
                        itemId: 'registerButton',
                        margin: '5px 0px',
                        padding: '10px',
                        ui: 'action',
                        text: 'Register'
                    },
                    {
                        xtype: 'label',
                        docked: 'top',
                        hidden: true,
                        hideAnimation: 'fadeOut',
                        html: 'Login failed. Please enter the correct credentials.',
                        itemId: 'signInFailedLabel',
                        showAnimation: 'fadeIn',
                        style: 'color:#990000;margin:20px 0px;'
                    },
                    {
                        xtype: 'button',
                        docked: 'bottom',
                        itemId: 'logInButton',
                        margin: '10px 0px',
                        padding: '10px',
                        ui: 'action',
                        text: 'Log In'
                    }
                ]
            }
        ]
    },

    showSignInFailedMessage: function(message) {
        console.log('-- showSignInFailedMessage --' + message);
        var label = this.down('#signInFailedLabel');
        console.log(' -- showSignInFailedMessage() : ' + label)
        label.setHtml(message);
        label.show();

    }

});