/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mainview',

    config: {
        zIndex: 100,
        items: [
            {
                xtype: 'container',
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'container',
                        height: '',
                        width: '50%',
                        layout: {
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                margin: '70% 10% 0% 20%',
                                padding: '25 0',
                                text: 'iCare'
                            },
                            {
                                xtype: 'button',
                                margin: '20% 10% 70% 20%',
                                padding: '25 0',
                                text: 'Profile'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        width: '50%',
                        layout: {
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                margin: '70% 20% 0% 10%',
                                padding: '25 0',
                                text: 'Carelendar'
                            },
                            {
                                xtype: 'button',
                                margin: '20% 20% 70% 10%',
                                padding: '25 0',
                                text: 'History'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});