/*
 * File: app/view/RegisterPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CareMe.view.RegisterPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.registerpanel',

    config: {
        items: [
            {
                xtype: 'fieldset',
                margin: '0px 10px',
                title: 'Register',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'userNameTextField',
                        label: '',
                        name: 'userNameTextField',
                        placeHolder: 'Username'
                    },
                    {
                        xtype: 'passwordfield',
                        itemId: 'passwordTextField',
                        label: '',
                        name: 'passwordTextField',
                        placeHolder: 'Password'
                    },
                    {
                        xtype: 'button',
                        docked: 'bottom',
                        itemId: 'cancel',
                        margin: '10px 0px',
                        padding: '10px',
                        ui: 'action',
                        text: 'Go Back'
                    },
                    {
                        xtype: 'button',
                        docked: 'bottom',
                        itemId: 'registerSubmit',
                        margin: '5px 0px',
                        padding: '10px',
                        ui: 'action',
                        text: 'Done!'
                    }
                ]
            }
        ]
    }

});