/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    models: [
        'Session'
    ],
    stores: [
        'SessionStore'
    ],
    views: [
        'MainView',
        'CarePanel',
        'CalendarPanel',
        'HistoryPanel',
        'LoginPanel',
        'RegisterPanel',
        'MyContainer',
        'ContactList',
        'CareList',
        'ShareList'
    ],
    controllers: [
        'UIController'
    ],
    name: 'CareMe',

    launch: function() {
        var _this = this;
        new Ext.util.DelayedTask(function () {
            Ext.Viewport.setMasked(false);
            Ext.Viewport.add([
            { xtype: 'loginpanel' },
            { xtype: 'mainview' },
            { xtype: 'registerpanel' }
            ]);

        }).delay(500);

        var store = Ext.getStore("SessionStore");



        store.load();

        debug = store;

        var session = store.first();

        if(session) {

            Ext.Ajax.request({
                url: 'http://192.168.0.103:9000/session',
                method: 'POST',
                params: {
                    'email':session.get("email"),
                    'session': session.get("session")
                },
                success: function(response) {
                    var text = response.responseText;
                    var json = JSON.parse(text);

                    if(json.status === "OK") {
                        Ext.Viewport.add({
                            xclass: 'CareMe.view.MainView'
                        });
                    } else {
                        _this.showLogin();
                    }
                },
                failure : function(response) {
                    Ext.Msg.alert('Error','Error while submitting the form');
                    var text = response.responseText;
                    var json = JSON.parse(text);
                    console.log(json);      
                }
            });
        } else {
            _this.showLogin();
        }


        /*
        if(Ext.browser.is.PhoneGap && !Ext.os.is.Desktop) {
        document.addEventListener("deviceready", this.mainLaunch, false);
        } else {
        this.mainLaunch();
        }
        */



    },

    showLogin: function() {
        Ext.Viewport.add({
            xclass: 'CareMe.view.LoginPanel'
        });
    },

    mainLaunch: function() {

    }

});
