/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    models: [
        'Session'
    ],
    views: [
        'MainView',
        'CarePanel',
        'CalendarPanel',
        'HistoryPanel',
        'LoginPanel',
        'RegisterPanel'
    ],
    controllers: [
        'UIController'
    ],
    name: 'CareMe',

    launch: function() {

        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            message: 'My Message'
        });
        new Ext.util.DelayedTask(function () {
            Ext.Viewport.setMasked(false);
            Ext.Viewport.add([
            { xtype: 'loginpanel' },
            { xtype: 'mainview' },
            { xtype: 'registerpanel' }
            ]);
            Ext.Viewport.add({
                xclass: 'CareMe.view.LoginPanel'
            });
        }).delay(1000);



        Ext.create('CareMe.view.LoginPanel', {fullscreen: true});
    }

});
